//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientForm.soap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="soap.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        clientForm.soap.obtenerCotizacionResponse obtenerCotizacion(clientForm.soap.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<clientForm.soap.obtenerCotizacionResponse> obtenerCotizacionAsync(clientForm.soap.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        clientForm.soap.registrarCotizacionResponse registrarCotizacion(clientForm.soap.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<clientForm.soap.registrarCotizacionResponse> registrarCotizacionAsync(clientForm.soap.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public clientForm.soap.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(clientForm.soap.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public clientForm.soap.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(clientForm.soap.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(decimal obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public clientForm.soap.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest() {
        }
        
        public registrarCotizacionRequest(clientForm.soap.registrarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public registrarCotizacionRequestBody() {
        }
        
        public registrarCotizacionRequestBody(string fecha, decimal monto) {
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public clientForm.soap.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse() {
        }
        
        public registrarCotizacionResponse(clientForm.soap.registrarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody() {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult) {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : clientForm.soap.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<clientForm.soap.WebServiceSoap>, clientForm.soap.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientForm.soap.obtenerCotizacionResponse clientForm.soap.WebServiceSoap.obtenerCotizacion(clientForm.soap.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public decimal obtenerCotizacion(string fecha) {
            clientForm.soap.obtenerCotizacionRequest inValue = new clientForm.soap.obtenerCotizacionRequest();
            inValue.Body = new clientForm.soap.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            clientForm.soap.obtenerCotizacionResponse retVal = ((clientForm.soap.WebServiceSoap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientForm.soap.obtenerCotizacionResponse> clientForm.soap.WebServiceSoap.obtenerCotizacionAsync(clientForm.soap.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientForm.soap.obtenerCotizacionResponse> obtenerCotizacionAsync(string fecha) {
            clientForm.soap.obtenerCotizacionRequest inValue = new clientForm.soap.obtenerCotizacionRequest();
            inValue.Body = new clientForm.soap.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((clientForm.soap.WebServiceSoap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientForm.soap.registrarCotizacionResponse clientForm.soap.WebServiceSoap.registrarCotizacion(clientForm.soap.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(string fecha, decimal monto) {
            clientForm.soap.registrarCotizacionRequest inValue = new clientForm.soap.registrarCotizacionRequest();
            inValue.Body = new clientForm.soap.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            clientForm.soap.registrarCotizacionResponse retVal = ((clientForm.soap.WebServiceSoap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientForm.soap.registrarCotizacionResponse> clientForm.soap.WebServiceSoap.registrarCotizacionAsync(clientForm.soap.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientForm.soap.registrarCotizacionResponse> registrarCotizacionAsync(string fecha, decimal monto) {
            clientForm.soap.registrarCotizacionRequest inValue = new clientForm.soap.registrarCotizacionRequest();
            inValue.Body = new clientForm.soap.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            return ((clientForm.soap.WebServiceSoap)(this)).registrarCotizacionAsync(inValue);
        }
    }
}
